apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storeapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeapi
  template:
    metadata:
      labels:
        app: storeapi
    spec:
      containers:
      - name: storeapi-container
        image:  mariors94/storeapi:4.0
        ports:                                     
        - containerPort: 8080                      
          name: http                                
kind: Service             
apiVersion: v1            
metadata:                 
  name: storeapi-service     
spec:                     
  selector:               
    app: storeapi           
  ports:                  
  - protocol: TCP         
    targetPort: 8080     
    port: 3000              
    name: http 
  type: ClusterIP